# Generated by Django 6.0.4 on 2026-05-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="branch",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="cgpa",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(default="test@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills",
            field=models.ManyToManyField(to="students.skill"),
        ),
    ]
