# Generated by Django 6.0.4 on 2026-05-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_rename_branch_studentprofile_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="points",
            field=models.IntegerField(default=10),
        ),
    ]
