# Generated by Django 6.0.4 on 2026-05-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_skill_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="points",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="cgpa",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
