# Generated by Django 6.0.4 on 2026-05-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_remove_skill_points_studentprofile_cgpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
