# Generated by Django 6.0.4 on 2026-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_studentprofile_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skills",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
