# Generated by Django 6.0.4 on 2026-05-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_remove_studentprofile_skills_studentprofile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="skills",
            field=models.TextField(blank=True),
        ),
    ]
