# Generated by Django 6.1 on 2026-08-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_cgpa', models.FloatField()),
                ('required_skills', models.CharField(max_length=200)),
            ],
        ),
    ]
