# Generated by Django 6.1 on 2026-08-07 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
