# Generated by Django 6.1 on 2026-08-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='hr_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='min_cgpa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='required_skills',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
